### ISSUE TITLE
Better API design

### ISSUE THREAD

**Issue by g105b** [PhpGt/Input#8]
UploadData should be included in the Input's internal `data` collection, so that it can be referred to in exactly the same way as query string or request body parameters.

The added benefit of this means that callbacks can be passed dynamic functions that can benefit from the type juggling of PHP.

To achieve this, all parameters (apart from extras passed in to `->call()`) need to be `InputDatum` types. An InputDatum is a representation of a single request KVP.

```php
$input->do("update-settings")
	->with("username", "password", "profile-photo")
	->call("saveSettings");

function saveSettings(string $username, string $password, FileUpload $profilePhoto) {
	// Dynamic properties with correct type, juggled by PHP.
}
```

**Comment by g105b** [comment]
`call` can only be used alongside `with`, otherwise it must throw an exception.

This is because, without `with`, `call` cannot know the order of parameters.

The exception should explain to the developer to use `callBundled` instead, which passes all parameters in a single bundled `InputData` parameter.

**Comment by christopher-paul-shaw** [comment]
Just pass the one input but allow $data->file to return type of FileUpload

**Comment by g105b** [comment]
Putting this on v3 as it is not a required feature for launch.

**Comment by g105b** [comment]
Implemented with new API design.
